assignment01: curse_main.cpp heap.c heap.h poke_logic.hpp poke_logic.cpp
	g++ curse_main.cpp heap.c poke_logic.cpp -o assignment01 -g -Wall -Werror -lncurses

clean:
	rm -f assignment01 *~ *.o core